ovsSwitch/ovsSwitch.go
ovsdbDriver/ovsdbDriver.go

1)Removing the sleep calls before GetOfPortno api usage
2) Modifying the GetOfPortno api to fetch the ofport directly from ovsdb .

Ofportno fix branch

---

ofctrl/fgraph.go
ofctrl/fgraphFlood.go
ofctrl/fgraphOutput.go
ofctrl/fgraphSwitch.go
ofctrl/fgraphTable.go
ofctrl/ofSwitch.go
ofnet.go
ofnetAgent.go
ovsdbDriver/ovsdbDriver.go
ovsdbDriver/ovsdbDriver_test.go
rpcHub/rpcHub.go
vlanBridge.go
vrouter.go
vxlanBridge.go

- policy in vlan mode
- Misc bug fixes
- gofmt all ofnet files

policy in vlan mode

---

ofnetAgent.go
ofnetBgp.go
vlanBridge.go

Minor fix to adapt to new netplugin changes

L3 integration for Containers (minor commit)

---

ofctrl/ofSwitch.go
ofnetPolicy.go

Small change to check for errors in rule action

add error checking for rule action

---

ofnet.go
ofnetAgent.go
ofnetBgp.go
ofnetPolicy_test.go
ofnet_test.go
vlrouter.go

The change contains:
1) decoupling bgp server start from ofnet agent instantiation
2) fixed unit cases to support the changes

Ofnet changes to support new netctl cli

---

vlrouter.go

minor fix to skip policy addition to bgp endpoints.

bypassing policy for bgp routes

---

ofnetBgp.go
ofnetPolicy.go
util.go

Improve ip address parsing in rules

---

.gitignore
Makefile
ofctrl/fgraphFlow.go
ofnet.go
ofnetAgent.go
ofnetSvcProxy.go
ofnetSvcProxy_test.go
pqueue/pqueue.go
pqueue/pqueue_test.go
vlanBridge.go
vlrouter.go
vrouter.go
vxlanBridge.go

Added service proxy implementation with IP affinity based load balancing. Watch flows are added for each service. When an EP accesses a service, corresponding [s,d]NAT flows are added.

Implement Service Proxy

---

vlanBridge.go

This change ignores any ARP packets that comes in on an uplink. The originator of the ARP request would have sent the packet to all uplinks and hence there is no need for re-injecting this packet again.

Ignore ARP processing from uplink in vlanBridge

---

ofnetAgent.go

We need to proxy for gateway in routing mode only.

arp proxy fix 

---

ofnetAgent.go
ofnetMaster.go
ofnetPolicy_test.go
ofnetSvcProxy_test.go
ofnet_test.go
rpcHub/rpcHub.go
vlanBridge.go
vrouter.go
vxlanBridge.go

Few misc bug fixes:
- Add an api for netmaster to add existing netplugins during restart
- Add a mutex for endpoint DB so that VTEP operations and Endpoint operations don't collide
- Misc fixes in RPC retry logic
- Gofmt some of the files..

Add nodeAdd() api to ofnetMaster and fix few bugs

---

ofnetSvcProxy.go

It is possible for an initial burst of packets to cause the same NAT flow to be added in succession. This PR adds a check in the local flow db for an existing flow before adding it.

Add a check for existing NAT flow before adding it

---

ofctrl/ofSwitch.go
ofnetAgent.go
vlanBridge.go

suppress per packet debug messages

supress pkt debug msgs

---

ofctrl/fgraphOutput.go
ofctrl/fgraphSwitch.go
ofnetAgent.go
ofnetMaster.go
ofnet_test.go
rpcHub/rpcHub.go

Go1.6 is exposing more concurrent map write problems. adding locks for most db modifications.

Add db locking to prevent concorrent modifications

---

ofnetAgent.go
ofnetSvcProxy.go
ofnetSvcProxy_test.go
vlanBridge.go
vrouter.go

Implement mac-rewrite to allow provider and client to be in the same sub-net.

Address https://github.com/contiv/ofnet/issues/28

---

ofnet.go
ofnetAgent.go
ofnetMaster.go
ofnetSvcProxy.go
ofnet_arp_test.go
ofnet_route_test.go
ofnet_test.go
ovsdbDriver/ovsdbDriver.go
vlanBridge.go
vlrouter.go
vrouter.go
vxlanBridge.go

- Add control plane stats 
- minor changes to svcStats
- add a way to test control plane functions like proxy ARP using stats
- split ofnet tests into multiple smaller files

Add control plane stats and tests

---

ofctrl/fgraphTable.go
ofnet.go
ofnetAgent.go
ofnetMaster.go
ovsdbDriver/ovsdbDriver.go
rpcHub/rpcHub.go

Add locking to various data structures based on race detection in integration and unit tests

Add locking based on issues found during race testing

---

ofnet.go
ofnetAgent.go
ofnetBgp.go

InspectBgp added

---

ofnet.go
ofnetAgent.go
ofnetSvcProxy.go
vlanBridge.go
vlrouter.go
vrouter.go
vxlanBridge.go

This is to make it friendly to collectors..

move svcstats to a map

---

vlrouter.go

verified with updated service tests in systemtest suite. corresponding netplugin changes to follow

Service load balancer support for L3 Bgp mode

---

ofnet.go
ofnetAgent.go
ofnetPolicy.go
ofnetPolicy_test.go
ofnet_flow_test.go
util.go
vlanBridge.go
vlrouter.go
vrouter.go
vxlanBridge.go

This PR is to rebases the changes from #60  and resubmit
- minor changes to the code to simplify it.
- add unit tests for setting up disc flows

Rebase and resubmit dscp changes

---

ofctrl/ofSwitch.go

Hit concurrent map issue with SwitchDB. Fixing it using concurrent-map

Fix switch DB concurrent map issue

---

ofnetBgp.go

PR contains fix for 
1) With ibgp peering routes were not distributed to the peer due the ASPATH being set. ASPATH only needs to be set for external peer route distribution
2) disable route distribution of the router ip

ibgp regression fix

---

Makefile

This PR makes a change to ensure we check all packages.

Makefile: add missing packages to check

---

ofctrl/fgraphTable.go
ofnet.go
ofnetAgent.go
ofnetSvcProxy_test.go
ofnet_route_test.go
ofnet_test.go
vlanBridge.go
vlrouter.go
vrouter.go
vxlanBridge.go

Signed-off-by: Joji Mekkatt <joji@cisco.com>
Add hostNAT port to vrouter in order to enable an exit path from overlay.

Add hostNAT to vrouter

---

ofctrl/ofctrl.go

This should fix the nil pointer dereferences we're occasionally seeing on CI.  Example:  https://contiv-ci.ngrok.io/job/Netplugin_CI/6902/console
Excerpt:
```
time="2017-04-11T22:31:55Z" level=info msg="New connection.." 
time="2017-04-11T22:31:55Z" level=info msg="Received Openflow 1.3 Hello message" 
time="2017-04-11T22:31:55Z" level=info msg="Removed uplink uplinkPort([eth2 eth3]) from OVS switch contivVlanBridge." 
time="2017-04-11T22:31:55Z" level=info msg="OfnetAgent: Received Delete" 
time="2017-04-11T22:31:55Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:434} DPID:00:00:ee:81:a2:88:b1:40 Buffers:256 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}" 
time="2017-04-11T22:31:55Z" level=info msg="Openflow …
```

ofctrl/ofctrl.go: fixed a race condition where the AppInterface could be cleared while connections were still being handled

---

vrouter.go

Fix missing nil check in vrouter.AddEndpoint
Signed-off-by: Mike Robinson <mikerob@cisco.com>

Fix issue 89

---

ofnetMaster.go

PR includes the following changes:
- Implement ClearNode function to reclaim endpoint resources and clear up flows on remote nodes
Usage:
This function can be used for GC when a particular node unexpectedly leaves the cluster. It will clear up the endpoint db and also removes flow(s) on the remote nodes.

Implement ClearNode to reclaim resources on node

---

Godeps/Godeps.json
vendor/github.com/contiv/libOpenflow/openflow13/match.go
vendor/github.com/contiv/libOpenflow/openflow13/openflow13.go

This PR bumps libOpenflow to include the PR https://github.com/contiv/libOpenflow/pull/3. This is part of the work needed to get contiv/netplugin#891 fixed.

Godeps,vendor: bump libOpenflow to cb1835d
